In [55]:
import pandas as pd

In [56]:
index = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,18]
result = pd.read_csv('Butterfly Past/past_search_result_1_2021-05-31.csv')
result = result[0:0]

for i in index:
    file = 'Butterfly Past/past_search_result_'+str(i)+'_2021-05-31.csv'
    df = pd.read_csv(file)
    #df = df[df['captcha_count']==11]
    result = result.append(df)

species = result['species'].tolist()
len(species)

95000

In [57]:
result

,species,found,URL,count,captcha_count
0,Eurema dammersi,False,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,0,6
1,Terias flava,False,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,0,1
2,Eurema pallens,False,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,0,6
3,Eurema callae,False,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,0,2
4,Papilio nicippe,False,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,0,1
...,...,...,...,...,...
4995,Ypthima fusca,False,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,0,4
4996,Ypthima gaugamela,False,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,0,7
4997,Ypthima gavalisi,False,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,0,2
4998,Ypthima granulosa,False,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,0,6
4999,Ypthima hanburyi,False,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,0,4

In [58]:
result[result['found']==True]

,species,found,URL,count,captcha_count
5,Eurema nicippe,True,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,1,1
489,Acraea servona,True,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,1,3
519,Acraea quirina,True,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,3,3
1037,Acraea eponina,True,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,2,9
1646,Adelpha melanthe,True,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,1,3
...,...,...,...,...,...
4780,Acrophtalmia leto,True,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,1,1
4861,Satyrus stheno,True,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,1,7
4863,Satyrus virbius,True,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,1,1
4871,Callerebia suroia,True,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,1,1
4907,Paralasa afghana,True,https://www.ebay.com/sch/i.html?_sacat=0&LH_So...,1,1